### ISSUE TITLE
Review abstract, intro and overview

### ISSUE THREAD

**Issue by ivotron** [michaelsevilla/sc16#17]
@michaelsevilla @noahdesu @carlosmalt  If you have time, can you please take a look at the abstract, and first 2 sections?
[main.pdf](https://github.com/michaelsevilla/sc16/files/211462/main.pdf)

**Comment by ivotron** [comment]
Here's [the PDF](https://github.com/michaelsevilla/sc16/files/211462/main.pdf)

**Comment by michaelsevilla** [comment]
Check out #19.

**Comment by ivotron** [comment]
those lgtm . Can you merge so I can rebase from my local branch?

**Comment by ivotron** [comment]
newest version [main.pdf](https://github.com/michaelsevilla/sc16/files/211678/main.pdf)

**Comment by ivotron** [comment]
fixed in #19
