### ISSUE TITLE
Choose title

### ISSUE THREAD

**Issue by ivotron** [michaelsevilla/sc16#2]
Alternatives:
  * The Popper Convention: Treating Academic Papers as Open Source Software Projects
  * GassyFS as a model for a reproducibility convention
  * The PasOSS convention: treating...
  * The XXX convention: treating.... with GassyFS as a use case
  * The XXX convention: common practices for reproducible research
  * The XXX convention: towards defining common practices for generating easily reproducible (falsibiable?) research

**Comment by ivotron** [comment]
@noahdesu @michaelsevilla @carlosmalt any other suggestions?

**Comment by noahdesu** [comment]
I like 1 and 5, but what is PasOSS. I think the title can only be about one subject, and if we add GassyFS to the title then it ends up sounding like it's something everyone should know about already...

**Comment by ivotron** [comment]
PasOSS is an acronym for Papers as Open Source Software. I agree, we might
need to leave GassyFS out of the title

**Comment by michaelsevilla** [comment]
I like 1... Is popper an acronym?

**Comment by ivotron** [comment]
I took popper from Karl Popper, who came up with the concept of
falsifiability

**Comment by carlosmalt** [comment]
Based on http://sc16.supercomputing.org/submitters/technical-papers/, the most appropriate tracks would be "Performance Measurement, Modeling, and Tools" and "Programming Systems" which both explicitly include reproducibility aspects in their list of topics. So the title should target those instead of our traditional track which was "Data Analytics, Visualization and Storage". Title 1 would be good if there was a "Systems Reproducibility" track -- but there isn't.

**Comment by carlosmalt** [comment]
Actually, "Programming systems" might be a stretch. So "Performance Measurement, Modeling, and Tools" -- if you have performance numbers.

**Comment by ivotron** [comment]
Yes, we have perf measurements in it. So based on your comment, something
like the following would work?

the popper convention: common practices for reproducible system performance
evaluation

**Comment by ivotron** [comment]
We could also submit to the "State-of-the-practice" track.

**Comment by carlosmalt** [comment]
Not sure whether this is "common practice" or a "state-of-the-practice report". You are introducing and extending DevOps practice to the computer systems research community. How about "Popper: making reproducible systems performance evaluation practical."

**Comment by ivotron** [comment]
I like it. thanks!
